# PostgreSQL. Versions 9.3 and up are supported.
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['TODO_LIST_DATABASE_USERNAME'] %>
  password: <%= ENV['TODO_LIST_DATABASE_PASSWORD'] %>
  host: localhost
  port: 5432

development:
  <<: *default
  database: todo_list_development

test:
  <<: *default
  database: todo_list_test

production:
  <<: *default
  database: todo_list_production
  username: todo_list
  password: <%= ENV["TODO_LIST_DATABASE_PASSWORD"] %>
